### ISSUE TITLE
Rails 6.1.1 undefined method `spec' error

### ISSUE THREAD

**Issue by Kuchick** [DatabaseCleaner/database_cleaner-active_record#48]
After upgrading Rails from 6.0.3.4 to 6.1.1 I got issues caused by changes in ActiveRecord.

Below is the code:
```DatabaseCleaner.strategy = :deletion
DatabaseCleaner[:active_record, connection: :test]
RSpec.configure do |config|
  config.before(:suite) do
    DatabaseCleaner.clean_with(:truncation, pre_count: true)
  end
  ...
end
```
and error stacktrace:
```
An error occurred in a `before(:suite)` hook.
Failure/Error: DatabaseCleaner.clean_with(:truncation, pre_count: true)

NoMethodError:
  undefined method `spec' for #<ActiveRecord::ConnectionAdapters::ConnectionPool:0x000055ae96b423d8>
  Did you mean?  inspect
.../gems/database_cleaner-1.8.5/adapters/database_cleaner-active_record/lib/database_cleaner/active_record/base.rb:91:in `block in lookup_from_connection_pool'
.../gems/database_cleaner-1.8.5/adapters/database_cleaner-active_record/lib/database_cleaner/active_record/base.rb:91:in `each'
.../gems/database_cleaner-1.8.5/adapters/database_cleaner-active_record/lib/database_cleaner/active_record/base.rb:91:in `detect'
.../gems/database_cleaner-1.8.5/adapters/database_cleaner-active_record/lib/database_cleaner/active_record/base.rb:91:in `lookup_from_connection_pool'
.../gems/database_cleaner-1.8.5/adapters/database_cleaner-active_record/lib/database_cleaner/active_record/base.rb:63:in `connection_class'
.../gems/database_cleaner-1.8.5/adapters/database_cleaner-active_record/lib/database_cleaner/active_record/truncation.rb:237:in `clean'
.../gems/database_cleaner-1.8.5/lib/database_cleaner/base.rb:61:in `clean_with'
.../gems/database_cleaner-1.8.5/lib/database_cleaner/configuration.rb:92:in `block in clean_with'
.../gems/database_cleaner-1.8.5/lib/database_cleaner/configuration.rb:92:in `each'
.../gems/database_cleaner-1.8.5/lib/database_cleaner/configuration.rb:92:in `clean_with'
# ./spec/support/database_cleaner.rb:8:in `block (2 levels) in <top (required)>'

```

**Comment by Kuchick** [comment]
Solution for this problem is in https://github.com/DatabaseCleaner/database_cleaner-active_record/pull/49

**Comment by botandrose** [comment]
Closed by #50
